from controllers import app, todos
from fastapi.testclient import TestClient

client = TestClient(app)


def setup_function():
    todos.clear()


def test_matches_id():
    puuid = (
        "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA"
    )
    response = client.get(f"/{puuid}/matches_id")
    assert response.status_code == 200
    assert response.json() == [
        "EUW1_6885901436",
        "EUW1_6885130495",
        "EUW1_6882372065",
        "EUW1_6882369675",
        "EUW1_6882343663",
        "EUW1_6882328723",
        "EUW1_6881101274",
        "EUW1_6881056435",
        "EUW1_6881026880",
        "EUW1_6880967680",
        "EUW1_6880848984",
        "EUW1_6880834181",
        "EUW1_6880478063",
        "EUW1_6880431131",
        "EUW1_6879026041",
        "EUW1_6878790908",
        "EUW1_6878748480",
        "EUW1_6878683631",
        "EUW1_6878485734",
        "EUW1_6878327068",
    ]


def test_matches_id_error():
    puuid = "dgGDGDGADGDG"
    response = client.get(f"/{puuid}/matches_id")
    assert response.status_code == 404
    assert response.json() == {
        "detail": {
            "status": {
                "status_code": 404,
                "message": "Data not found - No results found for player with riot this puuid dgGDGDGADGDG",
            }
        }
    }


def test_one_match():
    match_id = "EUW1_6885901436"
    response = client.get(f"/match?match_id={match_id}")
    assert response.status_code == 200
    assert response.json() == {
        "matchId": "EUW1_6885901436",
        "dataVersion": "2",
        "gameCreation": 1712257520269,
        "gameDuration": 653,
        "queueId": 1020,
        "participants": [
            {
                "summonerId": "yv0TVzzHD0tYLj2MUH0fp2olrbRnpcd-4NQ6DMeG5ifVpMU",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "aaRfygNTP7Jtw_GNTBpl2h7dDhcGP74feX3elb73Rcs5zd-80CBk8rLwk4AyPI29oAByfjbJ78geoA",
                "riotIdTagline": "EUW",
                "summonerLevel": 564,
                "summonerName": "Sigma ShadowMan",
                "champLevel": 10,
                "championName": "Thresh",
                "kills": 1,
                "assists": 20,
                "deaths": 2,
                "item0": 1055,
                "item1": 2065,
                "item2": 0,
                "item3": 3006,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 23,
                "spell2Casts": 11,
                "spell3Casts": 16,
                "spell4Casts": 3,
                "summoner1Id": 11,
                "summoner2Id": 4,
                "teamPosition": "JUNGLE",
                "totalMinionsKilled": 5,
                "win": True,
            },
            {
                "summonerId": "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA",
                "riotIdTagline": "EUW",
                "summonerLevel": 377,
                "summonerName": "Haruyukis",
                "champLevel": 9,
                "championName": "Thresh",
                "kills": 1,
                "assists": 20,
                "deaths": 0,
                "item0": 1055,
                "item1": 1036,
                "item2": 3222,
                "item3": 2031,
                "item4": 0,
                "item5": 0,
                "item6": 3364,
                "spell1Casts": 19,
                "spell2Casts": 15,
                "spell3Casts": 11,
                "spell4Casts": 1,
                "summoner1Id": 4,
                "summoner2Id": 11,
                "teamPosition": "UTILITY",
                "totalMinionsKilled": 7,
                "win": True,
            },
            {
                "summonerId": "oxtbCEvlCabSyP3d6SG6l6Da1eLo3oYOQhEr2Dyjfqkkt1w",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "f0EUEJknNW6L3RrR4_95iE3bvZHnON3gZhumsGu-UQqpob8w-pHFZZ7GgrlhjW8-C0aYRBe2ViaNqA",
                "riotIdTagline": "EUW",
                "summonerLevel": 239,
                "summonerName": "SûpêrNôvâ",
                "champLevel": 9,
                "championName": "Thresh",
                "kills": 4,
                "assists": 18,
                "deaths": 1,
                "item0": 3002,
                "item1": 3024,
                "item2": 1055,
                "item3": 1036,
                "item4": 3158,
                "item5": 2031,
                "item6": 3340,
                "spell1Casts": 25,
                "spell2Casts": 10,
                "spell3Casts": 19,
                "spell4Casts": 2,
                "summoner1Id": 4,
                "summoner2Id": 6,
                "teamPosition": "BOTTOM",
                "totalMinionsKilled": 3,
                "win": True,
            },
            {
                "summonerId": "AeQLLRNJkKKMn1pkpYf1P_9vHNKjeSpXOW0xUaQuDwV5bJw",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "RbECUFxi8KB5ziZJ092hgPZxbuo_L7CkY7KSEzRDQL1Sp4eZ-E_OJkVucnGT3rS1IPzpstFPw9BA4w",
                "riotIdTagline": "hook",
                "summonerLevel": 340,
                "summonerName": "DDcrow36",
                "champLevel": 10,
                "championName": "Thresh",
                "kills": 19,
                "assists": 5,
                "deaths": 0,
                "item0": 2015,
                "item1": 2031,
                "item2": 3074,
                "item3": 3006,
                "item4": 1018,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 17,
                "spell2Casts": 11,
                "spell3Casts": 24,
                "spell4Casts": 2,
                "summoner1Id": 6,
                "summoner2Id": 4,
                "teamPosition": "TOP",
                "totalMinionsKilled": 19,
                "win": True,
            },
            {
                "summonerId": "SSIbCty6kaNC0_XlVIsSQRRuxB3Rr4yNxAbQuB9bW63DprM",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "jClLqnmCBNEdTeUY2B3uBF_hJYyUjUeBKU_EjCo7YAmW_pi2CmpO2ZbrwjrVWx1c6PZdLSLb83YPcA",
                "riotIdTagline": "EUW",
                "summonerLevel": 633,
                "summonerName": "Lakilex777",
                "champLevel": 13,
                "championName": "Thresh",
                "kills": 2,
                "assists": 3,
                "deaths": 1,
                "item0": 3077,
                "item1": 2031,
                "item2": 1055,
                "item3": 6672,
                "item4": 3006,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 9,
                "spell2Casts": 5,
                "spell3Casts": 14,
                "spell4Casts": 3,
                "summoner1Id": 4,
                "summoner2Id": 6,
                "teamPosition": "MIDDLE",
                "totalMinionsKilled": 92,
                "win": True,
            },
            {
                "summonerId": "EUvoTeo4kw8CCSTlC7xNtnKC7Yc47CS0LVOpdylVpP3idtw",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "uKzO_urLe7MnVRTXfh2694iTXFlpB75OGj5mBtsB9_mzJvF2k2lyLaOk28ZaPlrpF-p85fIxwb_oxA",
                "riotIdTagline": "ROLL",
                "summonerLevel": 396,
                "summonerName": "DADS HOT NEW GF",
                "champLevel": 8,
                "championName": "Skarner",
                "kills": 0,
                "assists": 3,
                "deaths": 8,
                "item0": 6662,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 21,
                "spell2Casts": 12,
                "spell3Casts": 11,
                "spell4Casts": 3,
                "summoner1Id": 6,
                "summoner2Id": 4,
                "teamPosition": "UTILITY",
                "totalMinionsKilled": 10,
                "win": False,
            },
            {
                "summonerId": "9hOGvfqAPbmJM4l4La6Qe8hLUVbAPH0rb6CQP3OrR0ejoHH7",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "AAdlr0s_hkMpahACj62CingcrBBw6LBn6p8PLz0QGjKM_xJwKVn-Fe4PnkYVfAILTmH-oO9ao0BOXA",
                "riotIdTagline": "EUW",
                "summonerLevel": 580,
                "summonerName": "Idránel",
                "champLevel": 9,
                "championName": "Skarner",
                "kills": 0,
                "assists": 2,
                "deaths": 3,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 3084,
                "item4": 0,
                "item5": 3111,
                "item6": 3340,
                "spell1Casts": 45,
                "spell2Casts": 11,
                "spell3Casts": 7,
                "spell4Casts": 3,
                "summoner1Id": 4,
                "summoner2Id": 6,
                "teamPosition": "BOTTOM",
                "totalMinionsKilled": 34,
                "win": False,
            },
            {
                "summonerId": "q4QyZZ5K3Up9wNEhYCCXavf96_iaBjN5yLKOvfz2HlxqG4g",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "yYH5gHpbrGmRPmbAfIX0x8q8wNkdYiij5YOHZCMVokgQKYBw0ClALl45PGIOeNxw68ahpT-7T4QqfQ",
                "riotIdTagline": "EUW",
                "summonerLevel": 747,
                "summonerName": "D4D",
                "champLevel": 10,
                "championName": "Skarner",
                "kills": 0,
                "assists": 2,
                "deaths": 6,
                "item0": 3111,
                "item1": 3070,
                "item2": 6662,
                "item3": 1033,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 51,
                "spell2Casts": 17,
                "spell3Casts": 7,
                "spell4Casts": 2,
                "summoner1Id": 6,
                "summoner2Id": 4,
                "teamPosition": "TOP",
                "totalMinionsKilled": 38,
                "win": False,
            },
            {
                "summonerId": "UIpw-_256PO1aJYZMgJpUT5zF8w1exYtOoxqsG_mRbI6c0I",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "EVYzE0Oy_Qu8yNPhebM8RcA6RE_RCULgm00Xegzvki93DYcoqbuK_xryXF2QPFVgz9GZc62ZJOfUyg",
                "riotIdTagline": "EUW",
                "summonerLevel": 271,
                "summonerName": "intoxxication",
                "champLevel": 9,
                "championName": "Skarner",
                "kills": 1,
                "assists": 1,
                "deaths": 6,
                "item0": 3084,
                "item1": 3009,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 38,
                "spell2Casts": 16,
                "spell3Casts": 11,
                "spell4Casts": 3,
                "summoner1Id": 4,
                "summoner2Id": 6,
                "teamPosition": "JUNGLE",
                "totalMinionsKilled": 31,
                "win": False,
            },
            {
                "summonerId": "gybgIjyjWwdOrdC-SVJesc7kYfxiNOO3bXVePkUejfWFGubp",
                "matchId": "EUW1_6885901436",
                "summonerPuuid": "gwUsU_OLiVQAGvI-GnY0t-IYxALLzPlG7HxfhME3Cn6maUKrF_3nGGDPN-jscUS9fd4EzMKV43bdDg",
                "riotIdTagline": "EUW",
                "summonerLevel": 416,
                "summonerName": "R1pYOu",
                "champLevel": 11,
                "championName": "Skarner",
                "kills": 3,
                "assists": 1,
                "deaths": 4,
                "item0": 6662,
                "item1": 3111,
                "item2": 1057,
                "item3": 1031,
                "item4": 1028,
                "item5": 0,
                "item6": 3340,
                "spell1Casts": 43,
                "spell2Casts": 15,
                "spell3Casts": 12,
                "spell4Casts": 3,
                "summoner1Id": 6,
                "summoner2Id": 4,
                "teamPosition": "MIDDLE",
                "totalMinionsKilled": 46,
                "win": False,
            },
        ],
    }


def test_one_match_error():
    match_id = "GDGDDDLDML"
    response = client.get(f"/match?match_id={match_id}")
    assert response.status_code == 404
    assert response.json() == {
        "detail": {
            "status": {
                "status_code": 404,
                "message": "Data not found : The match id GDGDDDLDML requested doesn't exist.",
            }
        }
    }
