from fastapi.testclient import TestClient
from controllers import app, todos

client = TestClient(app)

def setup_function():
    todos.clear();

def test_summoner_by_name():
    summoner_name = "Haruyukis"
    tag = "EUW"
    response = client.get(f"/summoner/by-name/{summoner_name}/{tag}")
    assert response.status_code == 200
    assert response.json() == {"summonerId" : "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY", 
                               "summonerPuuid" : "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA", 
                               "summonerName" : "Haruyukis",
                               "summonerTag" : "EUW",
                               "summonerLevel" : 373,
                               "summonerProfileIconId" : 4660}

def test_summoner_by_puuid():
    puuid = "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA"
    response = client.get(f"/summoner/by-puuid/{puuid}")
    assert response.status_code == 200
    assert response.json() == {"summonerId" : "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY", 
                               "summonerPuuid" : "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA", 
                               "summonerName" : "Haruyukis",
                               "summonerTag" : "EUW",
                               "summonerLevel" : 373,
                               "summonerProfileIconId" : 4660}
    
def test_league():
    puuid = "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA"
    response = client.get(f"/league/{puuid}")
    assert response.status_code == 200
    assert response.json() == [
  {
    "summonerId": "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY",
    "summonerName": "Haruyukis",
    "queueType": "RANKED_SOLO_5x5",
    "tier": "MASTER",
    "rank": "I",
    "leaguePoints": 259,
    "wins": 58,
    "losses": 40
  },
  {
    "summonerId": "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY",
    "summonerName": "Haruyukis",
    "queueType": "RANKED_FLEX_SR",
    "tier": "MASTER",
    "rank": "I",
    "leaguePoints": 0,
    "wins": 31,
    "losses": 23
  }
]
    
def test_matches_id():
    puuid = "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA"
    response = client.get(f"/{puuid}/matches_id")
    assert response.status_code == 200
    assert response.json() == [
  "EUW1_6876151323",
  "EUW1_6875835868",
  "EUW1_6875824055",
  "EUW1_6875672482",
  "EUW1_6875501714",
  "EUW1_6875093494",
  "EUW1_6872654417",
  "EUW1_6872331227",
  "EUW1_6871559579",
  "EUW1_6871527505",
  "EUW1_6871460323",
  "EUW1_6871402182",
  "EUW1_6871364134",
  "EUW1_6871133374",
  "EUW1_6870986307",
  "EUW1_6869082641",
  "EUW1_6869012957",
  "EUW1_6867871973",
  "EUW1_6867839426",
  "EUW1_6867824903"
]

def test_one_match():
    match_id = "EUW1_6876151323"
    response = client.get(f"/match?match_id={match_id}")
    assert response.status_code == 200
    assert response.json() == {
  "metadata": {
    "dataVersion": "2",
    "matchId": "EUW1_6876151323",
    "participants": [
      "aaRfygNTP7Jtw_GNTBpl2h7dDhcGP74feX3elb73Rcs5zd-80CBk8rLwk4AyPI29oAByfjbJ78geoA",
      "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA",
      "f0EUEJknNW6L3RrR4_95iE3bvZHnON3gZhumsGu-UQqpob8w-pHFZZ7GgrlhjW8-C0aYRBe2ViaNqA",
      "8l-ADsoeM0JeJB6I_CevUHGJenzMkd-j4WCDprHK9Ate5p8OePnXR8Vvd9LbIOTR1VGjf0ztKMw9Zw",
      "SVKIU64-qx72x2x4f6n_metgtAzPg3vYhLg2k7H5u4l0D1xLE53ZNEyOrsR-gfC48gS_s_8Kz34MyA",
      "O8MfZ6EJZYUSlnOb_99YJcbvVpSJSKUZajObPPVbJdRGj1-OQiIWzMqIiPJeoMJ4hjxIEcsSAWllng",
      "wQ720cswfbm56ZIaBf8vGbI3gTjs5J4VdfI60kg_5Tdpcf6u_sUEphsyXrz0dZywssh_jxI5ghUCFg",
      "kQGBPdQRBcO3yzWHfVmUB_pWlkTGuhyzT84jA7GLCZPF3Tll9LuLQCSSnkVmydognVZ-IRbKcPVY3w",
      "fXi4qxh8Lm_SCvZGIu3m5mj1XvELMk2VnVGyolCBdiItO7_C_sq-cqoWA4OgdzbRej5zlksN22zDiA",
      "UcLizxGMLECX4oh5mzevReghUmPZ7Gq0Ej7lsCOc3ifMb7dZJITaof0tK0-_vpJppdQAeGpCpNwiPg"
    ]
  },
  "info": {
    "gameCreation": 1711665213972,
    "gameDuration": 1122,
    "gameEndTimestamp": 1711666394116,
    "gameId": 6876151323,
    "gameMode": "ONEFORALL",
    "gameName": "teambuilder-match-6876151323",
    "gameStartTimestamp": 1711665271478,
    "gameType": "MATCHED_GAME",
    "gameVersion": "14.6.570.6276",
    "mapId": 11,
    "participants": [
      {
        "allInPings": 0,
        "assistMePings": 1,
        "assists": 32,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 1,
        "champExperience": 15197,
        "champLevel": 16,
        "championId": 412,
        "championName": "Thresh",
        "championTransform": 0,
        "commandPings": 12,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 5655,
        "damageDealtToObjectives": 7243,
        "damageDealtToTurrets": 5655,
        "damageSelfMitigated": 19232,
        "dangerPings": 0,
        "deaths": 1,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 7,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 8542,
        "goldSpent": 5850,
        "holdPings": 0,
        "individualPosition": "JUNGLE",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 3077,
        "item1": 2065,
        "item2": 3006,
        "item3": 1053,
        "item4": 1055,
        "item5": 0,
        "item6": 3340,
        "itemsPurchased": 13,
        "killingSprees": 0,
        "kills": 1,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 816,
        "magicDamageDealt": 62022,
        "magicDamageDealtToChampions": 20667,
        "magicDamageTaken": 3455,
        "needVisionPings": 0,
        "neutralMinionsKilled": 7,
        "nexusKills": 1,
        "nexusLost": 0,
        "nexusTakedowns": 1,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 15,
        "participantId": 1,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5001,
            "offense": 5007
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8465,
                  "var1": 2451,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8463,
                  "var1": 1179,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8473,
                  "var1": 531,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8242,
                  "var1": 65,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8400
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8345,
                  "var1": 3,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8347,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8300
            }
          ]
        },
        "physicalDamageDealt": 17337,
        "physicalDamageDealtToChampions": 3582,
        "physicalDamageTaken": 4023,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 6051,
        "pushPings": 0,
        "puuid": "aaRfygNTP7Jtw_GNTBpl2h7dDhcGP74feX3elb73Rcs5zd-80CBk8rLwk4AyPI29oAByfjbJ78geoA",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 41,
        "spell2Casts": 16,
        "spell3Casts": 30,
        "spell4Casts": 5,
        "subteamPlacement": 0,
        "summoner1Casts": 11,
        "summoner1Id": 11,
        "summoner2Casts": 2,
        "summoner2Id": 4,
        "summonerId": "yv0TVzzHD0tYLj2MUH0fp2olrbRnpcd-4NQ6DMeG5ifVpMU",
        "summonerLevel": 562,
        "summonerName": "Sigma ShadowMan",
        "teamEarlySurrendered": False,
        "teamId": 100,
        "teamPosition": "TOP",
        "timeCCingOthers": 29,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 4,
        "totalDamageDealt": 86254,
        "totalDamageDealtToChampions": 24250,
        "totalDamageShieldedOnTeammates": 1960,
        "totalDamageTaken": 7479,
        "totalHeal": 2017,
        "totalHealsOnTeammates": 863,
        "totalMinionsKilled": 32,
        "totalTimeCCDealt": 114,
        "totalTimeSpentDead": 10,
        "totalUnitsHealed": 5,
        "tripleKills": 0,
        "trueDamageDealt": 6893,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 0,
        "turretKills": 4,
        "turretTakedowns": 7,
        "turretsLost": 8,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 6,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 4,
        "win": True
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 25,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 14383,
        "champLevel": 15,
        "championId": 412,
        "championName": "Thresh",
        "championTransform": 0,
        "commandPings": 5,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 2201,
        "damageDealtToObjectives": 3208,
        "damageDealtToTurrets": 2201,
        "damageSelfMitigated": 11689,
        "dangerPings": 0,
        "deaths": 2,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 1,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 7937,
        "goldSpent": 5850,
        "holdPings": 0,
        "individualPosition": "JUNGLE",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 1036,
        "item1": 1055,
        "item2": 3222,
        "item3": 3009,
        "item4": 3113,
        "item5": 4642,
        "item6": 3340,
        "itemsPurchased": 11,
        "killingSprees": 0,
        "kills": 1,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 476,
        "magicDamageDealt": 25677,
        "magicDamageDealtToChampions": 8444,
        "magicDamageTaken": 2987,
        "needVisionPings": 0,
        "neutralMinionsKilled": 9,
        "nexusKills": 0,
        "nexusLost": 0,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 16,
        "participantId": 2,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5001,
            "offense": 5007
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8465,
                  "var1": 1741,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8463,
                  "var1": 1523,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8473,
                  "var1": 652,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8242,
                  "var1": 49,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8400
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8345,
                  "var1": 3,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8347,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8300
            }
          ]
        },
        "physicalDamageDealt": 13315,
        "physicalDamageDealtToChampions": 1988,
        "physicalDamageTaken": 7026,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 4660,
        "pushPings": 0,
        "puuid": "HZjiCzLo8bFNuecnPFK1Jskchhq_h-q7xhFCfsmp1NA6FGK3kEeAyiKUbj0VAYHD97l6z5tz_ZU5OA",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 33,
        "spell2Casts": 29,
        "spell3Casts": 17,
        "spell4Casts": 5,
        "subteamPlacement": 0,
        "summoner1Casts": 3,
        "summoner1Id": 4,
        "summoner2Casts": 6,
        "summoner2Id": 11,
        "summonerId": "NGlurILZEiRx0MSuWmaQOX1ESvkdsuNGOFyTPoAROWhILpY",
        "summonerLevel": 375,
        "summonerName": "Haruyukis",
        "teamEarlySurrendered": False,
        "teamId": 100,
        "teamPosition": "UTILITY",
        "timeCCingOthers": 23,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 0,
        "totalDamageDealt": 42822,
        "totalDamageDealtToChampions": 10432,
        "totalDamageShieldedOnTeammates": 1987,
        "totalDamageTaken": 10013,
        "totalHeal": 1743,
        "totalHealsOnTeammates": 1202,
        "totalMinionsKilled": 21,
        "totalTimeCCDealt": 92,
        "totalTimeSpentDead": 51,
        "totalUnitsHealed": 5,
        "tripleKills": 0,
        "trueDamageDealt": 3829,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 0,
        "turretKills": 0,
        "turretTakedowns": 5,
        "turretsLost": 8,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 8,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 5,
        "win": True
      },
      {
        "allInPings": 0,
        "assistMePings": 3,
        "assists": 23,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 1,
        "champExperience": 13886,
        "champLevel": 15,
        "championId": 412,
        "championName": "Thresh",
        "championTransform": 0,
        "commandPings": 5,
        "consumablesPurchased": 2,
        "damageDealtToBuildings": 1382,
        "damageDealtToObjectives": 2377,
        "damageDealtToTurrets": 1382,
        "damageSelfMitigated": 14700,
        "dangerPings": 0,
        "deaths": 2,
        "detectorWardsPlaced": 1,
        "doubleKills": 1,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 2,
        "enemyVisionPings": 1,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 10156,
        "goldSpent": 9275,
        "holdPings": 0,
        "individualPosition": "JUNGLE",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 2065,
        "item1": 3190,
        "item2": 3107,
        "item3": 3067,
        "item4": 1055,
        "item5": 3158,
        "item6": 3340,
        "itemsPurchased": 20,
        "killingSprees": 1,
        "kills": 5,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 4,
        "largestMultiKill": 2,
        "longestTimeSpentLiving": 756,
        "magicDamageDealt": 36103,
        "magicDamageDealtToChampions": 14000,
        "magicDamageTaken": 3027,
        "needVisionPings": 0,
        "neutralMinionsKilled": 7,
        "nexusKills": 0,
        "nexusLost": 0,
        "nexusTakedowns": 1,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 3,
        "participantId": 3,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5008
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8351,
                  "var1": 60,
                  "var2": 1662,
                  "var3": 0
                },
                {
                  "perk": 8306,
                  "var1": 2,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8345,
                  "var1": 3,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8347,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8300
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8473,
                  "var1": 318,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8242,
                  "var1": 61,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8400
            }
          ]
        },
        "physicalDamageDealt": 11685,
        "physicalDamageDealtToChampions": 2088,
        "physicalDamageTaken": 5693,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 1376,
        "pushPings": 0,
        "puuid": "f0EUEJknNW6L3RrR4_95iE3bvZHnON3gZhumsGu-UQqpob8w-pHFZZ7GgrlhjW8-C0aYRBe2ViaNqA",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 49,
        "spell2Casts": 28,
        "spell3Casts": 31,
        "spell4Casts": 6,
        "subteamPlacement": 0,
        "summoner1Casts": 4,
        "summoner1Id": 4,
        "summoner2Casts": 1,
        "summoner2Id": 12,
        "summonerId": "oxtbCEvlCabSyP3d6SG6l6Da1eLo3oYOQhEr2Dyjfqkkt1w",
        "summonerLevel": 239,
        "summonerName": "SûpêrNôvâ",
        "teamEarlySurrendered": False,
        "teamId": 100,
        "teamPosition": "BOTTOM",
        "timeCCingOthers": 40,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 6,
        "totalDamageDealt": 48496,
        "totalDamageDealtToChampions": 16175,
        "totalDamageShieldedOnTeammates": 2836,
        "totalDamageTaken": 10720,
        "totalHeal": 2714,
        "totalHealsOnTeammates": 1063,
        "totalMinionsKilled": 31,
        "totalTimeCCDealt": 322,
        "totalTimeSpentDead": 78,
        "totalUnitsHealed": 4,
        "tripleKills": 0,
        "trueDamageDealt": 708,
        "trueDamageDealtToChampions": 86,
        "trueDamageTaken": 2000,
        "turretKills": 2,
        "turretTakedowns": 5,
        "turretsLost": 8,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 10,
        "visionWardsBoughtInGame": 1,
        "wardsKilled": 0,
        "wardsPlaced": 3,
        "win": True
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 6,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 28,
        "champExperience": 16398,
        "champLevel": 16,
        "championId": 412,
        "championName": "Thresh",
        "championTransform": 0,
        "commandPings": 1,
        "consumablesPurchased": 1,
        "damageDealtToBuildings": 11619,
        "damageDealtToObjectives": 13794,
        "damageDealtToTurrets": 11619,
        "damageSelfMitigated": 33702,
        "dangerPings": 0,
        "deaths": 0,
        "detectorWardsPlaced": 0,
        "doubleKills": 7,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 0,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 22788,
        "goldSpent": 14000,
        "holdPings": 0,
        "individualPosition": "JUNGLE",
        "inhibitorKills": 1,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 0,
        "item1": 3074,
        "item2": 3094,
        "item3": 3006,
        "item4": 3031,
        "item5": 3100,
        "item6": 3340,
        "itemsPurchased": 14,
        "killingSprees": 1,
        "kills": 28,
        "lane": "NONE",
        "largestCriticalStrike": 591,
        "largestKillingSpree": 28,
        "largestMultiKill": 4,
        "longestTimeSpentLiving": 0,
        "magicDamageDealt": 193266,
        "magicDamageDealtToChampions": 50726,
        "magicDamageTaken": 5521,
        "needVisionPings": 0,
        "neutralMinionsKilled": 37,
        "nexusKills": 0,
        "nexusLost": 0,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 4,
        "participantId": 4,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5005
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8021,
                  "var1": 2542,
                  "var2": 3387,
                  "var3": 0
                },
                {
                  "perk": 8009,
                  "var1": 3604,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 9104,
                  "var1": 6,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8014,
                  "var1": 2217,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8000
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8304,
                  "var1": 6,
                  "var2": 4,
                  "var3": 5
                },
                {
                  "perk": 8347,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8300
            }
          ]
        },
        "physicalDamageDealt": 71966,
        "physicalDamageDealtToChampions": 14981,
        "physicalDamageTaken": 4909,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 16,
        "pushPings": 0,
        "puuid": "8l-ADsoeM0JeJB6I_CevUHGJenzMkd-j4WCDprHK9Ate5p8OePnXR8Vvd9LbIOTR1VGjf0ztKMw9Zw",
        "quadraKills": 1,
        "riotIdTagline": "GSG",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 46,
        "spell2Casts": 24,
        "spell3Casts": 49,
        "spell4Casts": 6,
        "subteamPlacement": 0,
        "summoner1Casts": 3,
        "summoner1Id": 4,
        "summoner2Casts": 6,
        "summoner2Id": 6,
        "summonerId": "R_OS0Z0XQ3m14rrjUsYMVOR11ZEAkN9wey88S6PgPYxirEs",
        "summonerLevel": 375,
        "summonerName": "grizius98",
        "teamEarlySurrendered": False,
        "teamId": 100,
        "teamPosition": "JUNGLE",
        "timeCCingOthers": 29,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 29,
        "totalDamageDealt": 267067,
        "totalDamageDealtToChampions": 66944,
        "totalDamageShieldedOnTeammates": 1883,
        "totalDamageTaken": 10517,
        "totalHeal": 6905,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 138,
        "totalTimeCCDealt": 318,
        "totalTimeSpentDead": 0,
        "totalUnitsHealed": 1,
        "tripleKills": 2,
        "trueDamageDealt": 1834,
        "trueDamageDealtToChampions": 1236,
        "trueDamageTaken": 86,
        "turretKills": 0,
        "turretTakedowns": 6,
        "turretsLost": 8,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 4,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 3,
        "win": True
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 7,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 1,
        "champExperience": 16573,
        "champLevel": 17,
        "championId": 412,
        "championName": "Thresh",
        "championTransform": 0,
        "commandPings": 0,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 10417,
        "damageDealtToObjectives": 10417,
        "damageDealtToTurrets": 10417,
        "damageSelfMitigated": 17916,
        "dangerPings": 0,
        "deaths": 5,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 0,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": True,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 13021,
        "goldSpent": 11750,
        "holdPings": 0,
        "individualPosition": "MIDDLE",
        "inhibitorKills": 2,
        "inhibitorTakedowns": 2,
        "inhibitorsLost": 3,
        "item0": 3084,
        "item1": 3077,
        "item2": 3047,
        "item3": 6610,
        "item4": 3091,
        "item5": 1028,
        "item6": 3340,
        "itemsPurchased": 15,
        "killingSprees": 0,
        "kills": 2,
        "lane": "NONE",
        "largestCriticalStrike": 134,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 296,
        "magicDamageDealt": 71282,
        "magicDamageDealtToChampions": 9665,
        "magicDamageTaken": 10966,
        "needVisionPings": 0,
        "neutralMinionsKilled": 0,
        "nexusKills": 0,
        "nexusLost": 0,
        "nexusTakedowns": 1,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 0,
        "participantId": 5,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5001,
            "offense": 5005
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8437,
                  "var1": 1086,
                  "var2": 621,
                  "var3": 0
                },
                {
                  "perk": 8446,
                  "var1": 4882,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8429,
                  "var1": 35,
                  "var2": 15,
                  "var3": 11
                },
                {
                  "perk": 8451,
                  "var1": 251,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8400
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8009,
                  "var1": 1291,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 9105,
                  "var1": 12,
                  "var2": 30,
                  "var3": 0
                }
              ],
              "style": 8000
            }
          ]
        },
        "physicalDamageDealt": 33436,
        "physicalDamageDealtToChampions": 5041,
        "physicalDamageTaken": 9898,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 6504,
        "pushPings": 0,
        "puuid": "SVKIU64-qx72x2x4f6n_metgtAzPg3vYhLg2k7H5u4l0D1xLE53ZNEyOrsR-gfC48gS_s_8Kz34MyA",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "DUO",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 19,
        "spell2Casts": 20,
        "spell3Casts": 36,
        "spell4Casts": 5,
        "subteamPlacement": 0,
        "summoner1Casts": 3,
        "summoner1Id": 4,
        "summoner2Casts": 3,
        "summoner2Id": 12,
        "summonerId": "xuaBIt8LjJ7igm0ZXYUTrj0kJDOGL2-RES-ECaExdqCmrus",
        "summonerLevel": 634,
        "summonerName": "Punk Cremes",
        "teamEarlySurrendered": False,
        "teamId": 100,
        "teamPosition": "MIDDLE",
        "timeCCingOthers": 22,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 0,
        "totalDamageDealt": 115386,
        "totalDamageDealtToChampions": 14707,
        "totalDamageShieldedOnTeammates": 441,
        "totalDamageTaken": 20865,
        "totalHeal": 774,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 127,
        "totalTimeCCDealt": 186,
        "totalTimeSpentDead": 147,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 10667,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 0,
        "turretKills": 5,
        "turretTakedowns": 5,
        "turretsLost": 8,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 9,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 6,
        "win": True
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 1,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 10837,
        "champLevel": 13,
        "championId": 106,
        "championName": "Volibear",
        "championTransform": 0,
        "commandPings": 1,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 8762,
        "damageDealtToObjectives": 24309,
        "damageDealtToTurrets": 8762,
        "damageSelfMitigated": 22809,
        "dangerPings": 0,
        "deaths": 9,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 1,
        "eligibleForProgression": True,
        "enemyMissingPings": 0,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 3,
        "goldEarned": 9764,
        "goldSpent": 9350,
        "holdPings": 0,
        "individualPosition": "MIDDLE",
        "inhibitorKills": 1,
        "inhibitorTakedowns": 2,
        "inhibitorsLost": 3,
        "item0": 3153,
        "item1": 3111,
        "item2": 3181,
        "item3": 3067,
        "item4": 3211,
        "item5": 0,
        "item6": 3340,
        "itemsPurchased": 13,
        "killingSprees": 1,
        "kills": 2,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 2,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 213,
        "magicDamageDealt": 22655,
        "magicDamageDealtToChampions": 2636,
        "magicDamageTaken": 15817,
        "needVisionPings": 0,
        "neutralMinionsKilled": 12,
        "nexusKills": 0,
        "nexusLost": 1,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 0,
        "participantId": 6,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5005
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8008,
                  "var1": 27,
                  "var2": 6,
                  "var3": 0
                },
                {
                  "perk": 9111,
                  "var1": 133,
                  "var2": 60,
                  "var3": 0
                },
                {
                  "perk": 9104,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8299,
                  "var1": 357,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8000
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8446,
                  "var1": 2844,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8453,
                  "var1": 354,
                  "var2": 779,
                  "var3": 0
                }
              ],
              "style": 8400
            }
          ]
        },
        "physicalDamageDealt": 51114,
        "physicalDamageDealtToChampions": 5999,
        "physicalDamageTaken": 11247,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 4764,
        "pushPings": 0,
        "puuid": "O8MfZ6EJZYUSlnOb_99YJcbvVpSJSKUZajObPPVbJdRGj1-OQiIWzMqIiPJeoMJ4hjxIEcsSAWllng",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 35,
        "spell2Casts": 36,
        "spell3Casts": 29,
        "spell4Casts": 5,
        "subteamPlacement": 0,
        "summoner1Casts": 5,
        "summoner1Id": 4,
        "summoner2Casts": 6,
        "summoner2Id": 6,
        "summonerId": "uGWw5bJONmaEQc5hmt53izeZoV1R8wchsmZHyKAl79Q9ado",
        "summonerLevel": 388,
        "summonerName": "Crow On Head",
        "teamEarlySurrendered": False,
        "teamId": 200,
        "teamPosition": "MIDDLE",
        "timeCCingOthers": 12,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 4,
        "totalDamageDealt": 73770,
        "totalDamageDealtToChampions": 8635,
        "totalDamageShieldedOnTeammates": 1391,
        "totalDamageTaken": 27276,
        "totalHeal": 3934,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 66,
        "totalTimeCCDealt": 135,
        "totalTimeSpentDead": 264,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 0,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 211,
        "turretKills": 2,
        "turretTakedowns": 6,
        "turretsLost": 11,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 9,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 5,
        "win": False
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 4,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 12403,
        "champLevel": 14,
        "championId": 106,
        "championName": "Volibear",
        "championTransform": 0,
        "commandPings": 3,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 3195,
        "damageDealtToObjectives": 3195,
        "damageDealtToTurrets": 3195,
        "damageSelfMitigated": 34143,
        "dangerPings": 0,
        "deaths": 5,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 0,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": True,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 9532,
        "goldSpent": 9350,
        "holdPings": 0,
        "individualPosition": "BOTTOM",
        "inhibitorKills": 1,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 3121,
        "item1": 3084,
        "item2": 2031,
        "item3": 3111,
        "item4": 3075,
        "item5": 0,
        "item6": 3340,
        "itemsPurchased": 14,
        "killingSprees": 0,
        "kills": 2,
        "lane": "NONE",
        "largestCriticalStrike": 18,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 386,
        "magicDamageDealt": 34105,
        "magicDamageDealtToChampions": 4017,
        "magicDamageTaken": 20810,
        "needVisionPings": 0,
        "neutralMinionsKilled": 4,
        "nexusKills": 0,
        "nexusLost": 1,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 3,
        "participantId": 7,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5005
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8437,
                  "var1": 888,
                  "var2": 490,
                  "var3": 0
                },
                {
                  "perk": 8401,
                  "var1": 222,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8444,
                  "var1": 983,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8453,
                  "var1": 521,
                  "var2": 1016,
                  "var3": 0
                }
              ],
              "style": 8400
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 9105,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8009,
                  "var1": 1585,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8000
            }
          ]
        },
        "physicalDamageDealt": 27450,
        "physicalDamageDealtToChampions": 3623,
        "physicalDamageTaken": 11395,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 6027,
        "pushPings": 0,
        "puuid": "wQ720cswfbm56ZIaBf8vGbI3gTjs5J4VdfI60kg_5Tdpcf6u_sUEphsyXrz0dZywssh_jxI5ghUCFg",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 51,
        "spell2Casts": 44,
        "spell3Casts": 37,
        "spell4Casts": 5,
        "subteamPlacement": 0,
        "summoner1Casts": 2,
        "summoner1Id": 4,
        "summoner2Casts": 5,
        "summoner2Id": 3,
        "summonerId": "yWAG2xRuCr_XsUaJmbinD-CH7vwul0NM7VFR9TNkSCgmWToD",
        "summonerLevel": 222,
        "summonerName": "Fracking",
        "teamEarlySurrendered": False,
        "teamId": 200,
        "teamPosition": "BOTTOM",
        "timeCCingOthers": 20,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 0,
        "totalDamageDealt": 61555,
        "totalDamageDealtToChampions": 7641,
        "totalDamageShieldedOnTeammates": 1606,
        "totalDamageTaken": 32252,
        "totalHeal": 5033,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 57,
        "totalTimeCCDealt": 239,
        "totalTimeSpentDead": 117,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 0,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 46,
        "turretKills": 1,
        "turretTakedowns": 4,
        "turretsLost": 11,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 7,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 5,
        "win": False
      },
      {
        "allInPings": 0,
        "assistMePings": 4,
        "assists": 2,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 10512,
        "champLevel": 13,
        "championId": 106,
        "championName": "Volibear",
        "championTransform": 0,
        "commandPings": 32,
        "consumablesPurchased": 1,
        "damageDealtToBuildings": 7046,
        "damageDealtToObjectives": 7046,
        "damageDealtToTurrets": 7046,
        "damageSelfMitigated": 42588,
        "dangerPings": 0,
        "deaths": 10,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 2,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": True,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 10145,
        "goldSpent": 9950,
        "holdPings": 0,
        "individualPosition": "BOTTOM",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 3084,
        "item1": 8001,
        "item2": 3111,
        "item3": 3181,
        "item4": 1029,
        "item5": 0,
        "item6": 3340,
        "itemsPurchased": 16,
        "killingSprees": 0,
        "kills": 3,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 263,
        "magicDamageDealt": 23921,
        "magicDamageDealtToChampions": 4528,
        "magicDamageTaken": 31722,
        "needVisionPings": 1,
        "neutralMinionsKilled": 0,
        "nexusKills": 0,
        "nexusLost": 1,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 21,
        "participantId": 8,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5001,
            "offense": 5007
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8437,
                  "var1": 1070,
                  "var2": 581,
                  "var3": 0
                },
                {
                  "perk": 8446,
                  "var1": 3869,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8444,
                  "var1": 1869,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8453,
                  "var1": 409,
                  "var2": 976,
                  "var3": 0
                }
              ],
              "style": 8400
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8134,
                  "var1": 4,
                  "var2": 3,
                  "var3": 0
                },
                {
                  "perk": 8139,
                  "var1": 294,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8100
            }
          ]
        },
        "physicalDamageDealt": 24175,
        "physicalDamageDealtToChampions": 3924,
        "physicalDamageTaken": 14481,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 6502,
        "pushPings": 3,
        "puuid": "kQGBPdQRBcO3yzWHfVmUB_pWlkTGuhyzT84jA7GLCZPF3Tll9LuLQCSSnkVmydognVZ-IRbKcPVY3w",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 34,
        "spell2Casts": 38,
        "spell3Casts": 39,
        "spell4Casts": 6,
        "subteamPlacement": 0,
        "summoner1Casts": 3,
        "summoner1Id": 4,
        "summoner2Casts": 6,
        "summoner2Id": 6,
        "summonerId": "OwAJ5j4LAjBjbfWog93xGWDHgWgs79w3cexmVfwYvi8XFTq8",
        "summonerLevel": 45,
        "summonerName": "GenevievedKv",
        "teamEarlySurrendered": False,
        "teamId": 200,
        "teamPosition": "UTILITY",
        "timeCCingOthers": 17,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 0,
        "totalDamageDealt": 50066,
        "totalDamageDealtToChampions": 8453,
        "totalDamageShieldedOnTeammates": 1221,
        "totalDamageTaken": 46763,
        "totalHeal": 2052,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 38,
        "totalTimeCCDealt": 150,
        "totalTimeSpentDead": 239,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 1970,
        "trueDamageDealtToChampions": 0,
        "trueDamageTaken": 559,
        "turretKills": 3,
        "turretTakedowns": 5,
        "turretsLost": 11,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 2,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 2,
        "win": False
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 5,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 12153,
        "champLevel": 14,
        "championId": 106,
        "championName": "Volibear",
        "championTransform": 0,
        "commandPings": 1,
        "consumablesPurchased": 0,
        "damageDealtToBuildings": 6698,
        "damageDealtToObjectives": 6698,
        "damageDealtToTurrets": 6698,
        "damageSelfMitigated": 16081,
        "dangerPings": 0,
        "deaths": 7,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 0,
        "eligibleForProgression": True,
        "enemyMissingPings": 1,
        "enemyVisionPings": 0,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 0,
        "goldEarned": 9606,
        "goldSpent": 8700,
        "holdPings": 0,
        "individualPosition": "TOP",
        "inhibitorKills": 1,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 3,
        "item0": 1056,
        "item1": 3115,
        "item2": 3100,
        "item3": 3158,
        "item4": 3108,
        "item5": 1052,
        "item6": 3340,
        "itemsPurchased": 16,
        "killingSprees": 0,
        "kills": 1,
        "lane": "NONE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 404,
        "magicDamageDealt": 74980,
        "magicDamageDealtToChampions": 10738,
        "magicDamageTaken": 14320,
        "needVisionPings": 0,
        "neutralMinionsKilled": 15,
        "nexusKills": 0,
        "nexusLost": 1,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 10,
        "participantId": 9,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5008
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8005,
                  "var1": 1188,
                  "var2": 749,
                  "var3": 439
                },
                {
                  "perk": 9111,
                  "var1": 370,
                  "var2": 120,
                  "var3": 0
                },
                {
                  "perk": 9104,
                  "var1": 18,
                  "var2": 10,
                  "var3": 0
                },
                {
                  "perk": 8014,
                  "var1": 287,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8000
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8143,
                  "var1": 590,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8106,
                  "var1": 4,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8100
            }
          ]
        },
        "physicalDamageDealt": 16869,
        "physicalDamageDealtToChampions": 2771,
        "physicalDamageTaken": 6739,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 1640,
        "pushPings": 0,
        "puuid": "fXi4qxh8Lm_SCvZGIu3m5mj1XvELMk2VnVGyolCBdiItO7_C_sq-cqoWA4OgdzbRej5zlksN22zDiA",
        "quadraKills": 0,
        "riotIdTagline": "DOG",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 32,
        "spell2Casts": 31,
        "spell3Casts": 37,
        "spell4Casts": 6,
        "subteamPlacement": 0,
        "summoner1Casts": 5,
        "summoner1Id": 6,
        "summoner2Casts": 3,
        "summoner2Id": 4,
        "summonerId": "3kfS3MK2AUXWsrPBjxCCpujJYoMWrEc72abPJoWRysTqs8Q",
        "summonerLevel": 534,
        "summonerName": "ZOB MAN",
        "teamEarlySurrendered": False,
        "teamId": 200,
        "teamPosition": "JUNGLE",
        "timeCCingOthers": 13,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 7,
        "totalDamageDealt": 91881,
        "totalDamageDealtToChampions": 13542,
        "totalDamageShieldedOnTeammates": 999,
        "totalDamageTaken": 21154,
        "totalHeal": 2065,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 80,
        "totalTimeCCDealt": 114,
        "totalTimeSpentDead": 190,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 32,
        "trueDamageDealtToChampions": 32,
        "trueDamageTaken": 94,
        "turretKills": 1,
        "turretTakedowns": 3,
        "turretsLost": 11,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 5,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 4,
        "win": False
      },
      {
        "allInPings": 0,
        "assistMePings": 0,
        "assists": 3,
        "baronKills": 0,
        "basicPings": 0,
        "bountyLevel": 0,
        "champExperience": 12552,
        "champLevel": 14,
        "championId": 106,
        "championName": "Volibear",
        "championTransform": 0,
        "commandPings": 3,
        "consumablesPurchased": 2,
        "damageDealtToBuildings": 2349,
        "damageDealtToObjectives": 13878,
        "damageDealtToTurrets": 2349,
        "damageSelfMitigated": 39919,
        "dangerPings": 0,
        "deaths": 7,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 1,
        "eligibleForProgression": True,
        "enemyMissingPings": 0,
        "enemyVisionPings": 1,
        "firstBloodAssist": False,
        "firstBloodKill": False,
        "firstTowerAssist": False,
        "firstTowerKill": False,
        "gameEndedInEarlySurrender": False,
        "gameEndedInSurrender": False,
        "getBackPings": 2,
        "goldEarned": 8797,
        "goldSpent": 8600,
        "holdPings": 0,
        "individualPosition": "TOP",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 0,
        "inhibitorsLost": 3,
        "item0": 3111,
        "item1": 2502,
        "item2": 3065,
        "item3": 3076,
        "item4": 1028,
        "item5": 1054,
        "item6": 3340,
        "itemsPurchased": 21,
        "killingSprees": 0,
        "kills": 1,
        "lane": "NONE",
        "largestCriticalStrike": 4,
        "largestKillingSpree": 0,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 385,
        "magicDamageDealt": 27004,
        "magicDamageDealtToChampions": 3686,
        "magicDamageTaken": 21124,
        "needVisionPings": 0,
        "neutralMinionsKilled": 8,
        "nexusKills": 0,
        "nexusLost": 1,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "onMyWayPings": 4,
        "participantId": 10,
        "pentaKills": 0,
        "perks": {
          "statPerks": {
            "defense": 5001,
            "flex": 5008,
            "offense": 5005
          },
          "styles": [
            {
              "description": "primaryStyle",
              "selections": [
                {
                  "perk": 8005,
                  "var1": 516,
                  "var2": 257,
                  "var3": 258
                },
                {
                  "perk": 9111,
                  "var1": 171,
                  "var2": 80,
                  "var3": 0
                },
                {
                  "perk": 9105,
                  "var1": 0,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8299,
                  "var1": 340,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8000
            },
            {
              "description": "subStyle",
              "selections": [
                {
                  "perk": 8234,
                  "var1": 9830,
                  "var2": 0,
                  "var3": 0
                },
                {
                  "perk": 8232,
                  "var1": 2,
                  "var2": 0,
                  "var3": 0
                }
              ],
              "style": 8200
            }
          ]
        },
        "physicalDamageDealt": 27002,
        "physicalDamageDealtToChampions": 2568,
        "physicalDamageTaken": 10082,
        "placement": 0,
        "playerAugment1": 0,
        "playerAugment2": 0,
        "playerAugment3": 0,
        "playerAugment4": 0,
        "playerSubteamId": 0,
        "profileIcon": 548,
        "pushPings": 0,
        "puuid": "UcLizxGMLECX4oh5mzevReghUmPZ7Gq0Ej7lsCOc3ifMb7dZJITaof0tK0-_vpJppdQAeGpCpNwiPg",
        "quadraKills": 0,
        "riotIdTagline": "EUW",
        "role": "SUPPORT",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 32,
        "spell2Casts": 42,
        "spell3Casts": 37,
        "spell4Casts": 4,
        "subteamPlacement": 0,
        "summoner1Casts": 2,
        "summoner1Id": 6,
        "summoner2Casts": 3,
        "summoner2Id": 4,
        "summonerId": "qPFnXc9F_7vCd06q7E0rm5y-5Ovwg3hxKkHAQMtK6MmGP0w",
        "summonerLevel": 323,
        "summonerName": "00unknown00",
        "teamEarlySurrendered": False,
        "teamId": 200,
        "teamPosition": "TOP",
        "timeCCingOthers": 16,
        "timePlayed": 1122,
        "totalAllyJungleMinionsKilled": 4,
        "totalDamageDealt": 54118,
        "totalDamageDealtToChampions": 6309,
        "totalDamageShieldedOnTeammates": 1615,
        "totalDamageTaken": 31617,
        "totalHeal": 4443,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 59,
        "totalTimeCCDealt": 207,
        "totalTimeSpentDead": 147,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 110,
        "trueDamageDealtToChampions": 54,
        "trueDamageTaken": 411,
        "turretKills": 1,
        "turretTakedowns": 3,
        "turretsLost": 11,
        "unrealKills": 0,
        "visionClearedPings": 0,
        "visionScore": 7,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 0,
        "wardsPlaced": 5,
        "win": False
      }
    ],
    "platformId": "EUW1",
    "queueId": 1020,
    "teams": [
      {
        "bans": [
          {
            "championId": 234,
            "pickTurn": 1
          },
          {
            "championId": 122,
            "pickTurn": 2
          },
          {
            "championId": 901,
            "pickTurn": 3
          },
          {
            "championId": 200,
            "pickTurn": 4
          },
          {
            "championId": 350,
            "pickTurn": 5
          }
        ],
        "objectives": {
          "baron": {
            "first": False,
            "kills": 0
          },
          "champion": {
            "first": True,
            "kills": 38
          },
          "dragon": {
            "first": False,
            "kills": 0
          },
          "inhibitor": {
            "first": False,
            "kills": 3
          },
          "riftHerald": {
            "first": False,
            "kills": 0
          },
          "tower": {
            "first": False,
            "kills": 11
          }
        },
        "teamId": 100,
        "win": True
      },
      {
        "bans": [
          {
            "championId": 35,
            "pickTurn": 6
          },
          {
            "championId": 74,
            "pickTurn": 7
          },
          {
            "championId": 32,
            "pickTurn": 8
          },
          {
            "championId": 154,
            "pickTurn": 9
          },
          {
            "championId": 266,
            "pickTurn": 10
          }
        ],
        "objectives": {
          "baron": {
            "first": False,
            "kills": 0
          },
          "champion": {
            "first": False,
            "kills": 10
          },
          "dragon": {
            "first": True,
            "kills": 2
          },
          "inhibitor": {
            "first": True,
            "kills": 3
          },
          "riftHerald": {
            "first": False,
            "kills": 0
          },
          "tower": {
            "first": True,
            "kills": 8
          }
        },
        "teamId": 200,
        "win": False
      }
    ],
    "tournamentCode": ""
  }
}